//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int ProductID { get; set; }
        public int CategoryID { get; set; }  
        public Nullable<int> OrderID { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
        public int Quantity { get; set; }

        [Range(1, 9999.99, ErrorMessage = "Rate must be between 1 and 9999.99")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Rate must be a valid number with up to 2 decimal places")]
        public decimal Rate { get; set; }

        public virtual OrderMaster OrderMaster { get; set; }
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
    }
}
