//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductID { get; set; }


        [Required(ErrorMessage = "You can't leave it blank.")]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Enter minimum 2 or maximum 40 char.")]
        [Display(Name = "Product Name", Description = "Name of the Product")]
        public string ProductName { get; set; }

        public int CategoryID { get; set; }
    }
}
